booking/booking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', auth_views.LoginView.as_view()),
    path('', include('flights.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking/flights/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('sign-up/', views.sign_up, name='signup'),
    path('log-in/', views.log_in, name='login'),
    path('log-out/', views.log_out, name='logout'),
    path('profile/', views.profile_page, name='profile'),
    path('search/', views.ticket_search, name='search'),
    path('booking/<int:id>', views.ticket_booking, name='booking-ticket'),
    path('booked/', views.ticket_booking, name='booked-ticket'),
    path('ajax/load-airports/', views.load_airports, name='ajax_load_airports'),
    path('edit/', views.edit_profile, name='edit-profile'),
    path('booked-tickets/', views.booked_tickets, name='booked'),
    path('delete_order/<str:pk>', views.delete, name='delete'),
    path('messages/', views.message_for_admin, name='messages'),
    path('messages-list/', views.admin_message_list, name='admin-list'),
    path('chat/<int:id>', views.chat, name='chat')
]

booking/flights/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    image = models.ImageField(upload_to='profile_pics/', default='profile_pics/default.jpg')
    birthday = models.DateField(default=None, name='birthday', null=True)

    def __str__(self):
        return f'{self.user.username} profile'

    # def save(self):
    #     super().save()
    #
    #     img = Image.open(self.image.path)

        # if img.height > 500 or img.width > 500:
        #     output_size = (500, 500)
        #     img.thumbnail(output_size)
        #     img.save(self.image.path)


class City(models.Model):
    city = models.CharField(max_length=100, null=True)

    def __str__(self):
        return f"{self.city}"


class Airport(models.Model):
    city_airport = models.ForeignKey(City, on_delete=models.CASCADE, related_name='cities')
    title = models.CharField(max_length=100)
    code = models.CharField(max_length=3)

    def __str__(self):
        return f"{self.title}"


class Flight(models.Model):
    departure_city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='departure_city', blank=True, null=True)
    departure_airport = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name='departure_air',
                                          blank=True, null=True)
    destination_city = models.ForeignKey(City, on_delete=models.CASCADE, related_name='destination_city', blank=True, null=True)
    destination_airport = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name='destination_air',
                                            blank=True, null=True)
    seats_count = models.IntegerField(blank=True, default=None)
    departure_date = models.DateField(blank=True, null=True, default=None)
    departure_time = models.TimeField(blank=True, null=True, default=None)
    arrival_date = models.DateField(blank=True, null=True, default=None)
    arrival_time = models.TimeField(blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=4, decimal_places=0, blank=True, default=None)
    is_available = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.departure_city} ({self.departure_airport}) — {self.destination_city} ({self.destination_airport}): {self.departure_date}"

    def update_seats(self):
        if self.seats_count == 0:
            self.is_available = False
        else:
            self.is_available = True
        self.save()


class Ticket(models.Model):
    flight = models.ForeignKey(Flight, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=50, null=True)
    last_name = models.CharField(max_length=50, null=True)
    email = models.EmailField(max_length=50, null=True)
    phone = models.CharField(default=None, max_length=50, null=True)
    birthday = models.DateField(default=None, name='birthday', null=True)


    def __str__(self):
        return f"{self.flight}"


class Order(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    paid = models.BooleanField(default=False)

    def __str__(self):
        return 'Order {}'.format(self.id)


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    ticket = models.ForeignKey(Ticket, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=4, decimal_places=2)

    def __str__(self):
        return '{}'.format(self.id)


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="sender")
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="recipient")
    text = models.CharField(max_length=240)
    created_at = models.DateTimeField(auto_now_add=True)

booking/flights/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Ticket, Order, Airport, Profile, Flight, Message
from django.forms import Form, PasswordInput, CharField, ModelForm
from django.core.validators import RegexValidator


class LoginForm(Form):
    username = CharField(label='Username')
    password = CharField(label='Password', widget=PasswordInput())


class UserForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']


class SearchForm(forms.ModelForm):
    class Meta:
        model = Flight
        fields = ['departure_city', 'departure_airport', 'destination_city', 'destination_airport', 'departure_date',
                  'arrival_date', 'price']
        widgets = {
            "departure_date": forms.DateInput(attrs={'type': 'date'}, format=settings.DATE_INPUT_FORMATS),
            "arrival_date": forms.DateInput(attrs={'type': 'date'}, format=settings.DATE_INPUT_FORMATS),
            "price": forms.NumberInput(attrs={'type': 'range', 'step': '10', 'min': '50', 'max': '700', 'value': '700', 'id': 'range-field'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['departure_airport'].queryset = Airport.objects.none()
        self.fields['destination_airport'].queryset = Airport.objects.none()

        if 'departure_city' in self.data:
            try:
                city_airport_id = int(self.data.get('departure_city'))
                self.fields['departure_airport'].queryset = Airport.objects.filter(city_airport_id=city_airport_id).order_by('title')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['departure_airport'].queryset = self.instance.departure_city.departure_airport_set.order_by('title')

        if 'destination_city' in self.data:
            try:
                city_airport_id = int(self.data.get('destination_city'))
                self.fields['destination_airport'].queryset = Airport.objects.filter(city_airport_id=city_airport_id).order_by('title')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['destination_airport'].queryset = self.instance.destination_city.destination_airport_set.order_by('title')


class OrderForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ('first_name', 'last_name', 'email')
        widgets = {
            "birthday": forms.DateInput(attrs={'type': 'date'}, format=settings.DATE_INPUT_FORMATS),
        }


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email',)


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('image', 'birthday',)
        widgets = {
            "birthday": forms.DateInput(attrs={'type': 'date'}),
        }


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['text']
        widgets = {
            "text": forms.Textarea(attrs={'width': '400px', 'cols': '40', 'rows': '4'})
        }
        labels = {
            'text': 'Message:',
        }

booking/flights/views.py
from datetime import date

from django.db.models import Count, Q
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from djoser.conf import User
from .forms import UserForm, LoginForm, SearchForm, OrderForm, UserUpdateForm, ProfileUpdateForm, MessageForm
from django.contrib import messages


from .models import Ticket, Profile, Airport, City, Flight, Message


def index(request):
    return render(request, 'index.html')


@login_required(login_url='/log-in')
def about(request):
    return render(request, 'about.html')


def sign_up(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('first_name')
            messages.success(request, 'Your profile is created,' + ' ' + user)
            return redirect('login')
    else:
        form = UserForm()
    return render(request, 'sign_up.html', {'form': form})


def log_in(request):
    error = ''
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(password=data['password'], username=data['username'])
            if user is not None:
                login(request, user)
                return redirect('profile')
            else:
                return redirect('login')
        else:
            error = 'ERROR!'
    else:
        form = LoginForm()
    return render(request, 'log_in.html', {
        'form': form,
        'error': error,
    })


def log_out(request):
    logout(request)
    return redirect('home')


@login_required
def profile_page(request):
    return render(request, 'profile.html')


@login_required(login_url='/log-in')
def edit_profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Your profile is updated successfully!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'profile_edit.html', context)


def ticket_search(request):
    queryset = Flight.objects.filter(is_available=True).filter(departure_date__gte=date.today())
    form = SearchForm(request.GET)
    if form.is_valid():
        if form.cleaned_data['departure_city']:
            queryset = queryset.filter(departure_city=form.cleaned_data['departure_city'])
        if form.cleaned_data['departure_airport']:
            queryset = queryset.filter(departure_airport=form.cleaned_data['departure_airport'])
        if form.cleaned_data['destination_city']:
            queryset = queryset.filter(destination_city=form.cleaned_data['destination_city'])
        if form.cleaned_data['destination_airport']:
            queryset = queryset.filter(destination_airport=form.cleaned_data['destination_airport'])
        for flight in queryset:
            if flight.departure_date > date.today() or flight.departure_date == date.today():
                if form.cleaned_data['departure_date']:
                    queryset = queryset.filter(departure_date=form.cleaned_data['departure_date'])
        for flight in queryset:
            if flight.arrival_date > flight.departure_date or flight.arrival_date == flight.departure_date:
                if form.cleaned_data['arrival_date']:
                    queryset = queryset.filter(arrival_date=form.cleaned_data['arrival_date'])
        if form.cleaned_data['price'] or form.cleaned_data['price'] == 0:
            queryset = queryset.filter(price__lte=form.cleaned_data['price'])
    return render(request, 'ticket_search.html', {"queryset": queryset, "form": form})


@login_required(login_url='/log-in')
def ticket_booking(request, id):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.flight = Flight.objects.get(pk=id)
            if ticket.flight.seats_count > 0:
                ticket.flight.seats_count -= 1
                ticket.flight.update_seats()
            else:
                messages.error(request, 'Error! There is no seats on this flight')
                ticket.flight.update_seats()
                return redirect('search')
            ticket.user = request.user
            ticket.save()
            ticket.flight.save()
            return render(request, 'ticket_booked.html', )
        else:
            form = OrderForm()
            return render(request, 'ticket_booking.html', {'form': form})
    person_instance = User.objects.get(profile=request.user.profile)
    form = OrderForm(instance=person_instance)
    return render(request, 'ticket_booking.html', {'form': form})


def load_airports(request):
    city_airport_id = request.GET.get('city_airport_id')
    airports = Airport.objects.filter(city_airport_id=city_airport_id).all()
    return render(request, 'dropdown_list.html', {'airports': airports})


def booked_tickets(request):
    ticket = Ticket.objects.all().filter(user=request.user)
    return render(request, 'booked_tickets.html', {"ticket": ticket})


def delete(request, pk):
    ticket = Ticket.objects.get(id=pk)
    ticket_flight = ticket.flight
    if request.method == "POST":
        ticket.delete()
        ticket_flight.seats_count += 1
        ticket_flight.update_seats()
        return redirect('booked')
    return render(request, 'delete_order.html', {'item': ticket})


def message_for_admin(request):
    sender = request.user
    recipient = User.objects.get(id=1)
    message_list = Message.objects.filter(Q(sender=sender) | Q(recipient=sender))
    if request.method == "POST":
        form = MessageForm(request.POST)
        message = form.save(commit=False)
        message.sender = sender
        message.recipient = recipient
        message.save()
    else:
        form = MessageForm()
    return render(request, 'message_for_admin.html',
                  {"message_list": message_list, "form": form, "sender": sender, "recipient": recipient})


def admin_message_list(request):
    message_list = Message.objects.values('sender_id__first_name', 'sender_id').annotate(recipient_messages=Count('sender'))
    return render(request, 'admin_message_list.html', {"message_list": message_list})


def chat(request, id):
    sender = request.user
    recipient = User.objects.get(id=id)
    message_list = Message.objects.filter(Q(sender=recipient) | Q(recipient=recipient))
    if request.method == "POST":
        # import pdb; pdb.set_trace()
        form = MessageForm(request.POST)
        message = form.save(commit=False)
        message.sender = sender
        message.recipient = recipient
        message.save()
    else:
        form = MessageForm()
    return render(request, 'message_for_admin.html', {"message_list": message_list, "form": form})

booking/flights/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% csrf_token %}

<h1 align="center" style="padding:30px">FLIGHTS</h1>



{% endblock %}

booking/flights/templates/admin_message_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 align="center" style="color: #0d5528; font-weight: bold; padding: 20px">Message list</h2>
{% for message in message_list %}
 <div class="content-section" align="center">
        <div class="list-group" align="center" style="display: inline-block; margin: 5px">
            <a href="{% url 'chat' message.sender_id %}" class="list-group-item list-group-item-action"><i class="fa-regular fa-paper-plane" style="color: #0d5528"></i> {{ message.sender_id__first_name }}</a>
        </div>
    </div>
{% endfor %}

{% endblock %}

booking/flights/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'flight/main.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;800&family=Poppins:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://kit.fontawesome.com/581e5574d2.css" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/581e5574d2.js" crossorigin="anonymous"></script>
    <title>{% block title %}FLIGHTS{% endblock %}</title>
</head>
   <header style="background: white" class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-2 mb-2 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
      </a>
       <div class="float-start" align="left">
            <a href="/">
                <img src="/static/flight/plane.png" width="40" height="40px" align="left"/>
            </a>
       </div>
        <h3 style="color: #0d5528">FLIGHTS</h3>
       {% if request.user.is_authenticated and request.user.is_superuser %}
       <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'admin-list' %}" class="nav-link px-2" style="color: #0d5528">Messages</a></li>
      </ul>
       {% else %}
       <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'search' %}" class="nav-link px-2" style="color: #0d5528">Search for tickets</a></li>
      </ul>
       {% endif %}

       {% if request.user.is_authenticated %}
       <div class="col-md-4 text-end text-center justify-content-center col-md-auto mb-md-1" >
           <a href="{% url 'profile' %}" style="color: #0d5528">{{user.username}}</a> | <a href="{% url 'logout' %}" class="btn btn-primary" style="background-color: #0d5528; --bs-btn-border-color: white; --bs-btn-hover-border-color:green; border-radius: 50px" >Logout</a>
       </div>
       {% else %}
      <div class="col-md-3 text-right">
            <a href="{% url 'login' %}" type="button" class="btn btn-outline-primary me-2" style="background-color: white; --bs-btn-border-color: #0d5528; --bs-btn-color: #0d5528; --bs-btn-hover-border-color:green; border-radius: 50px">Login</a>
            <a href="{% url 'signup' %}" type="button" class="btn btn-primary" style="background-color: #0d5528; --bs-btn-border-color: white; --bs-btn-hover-border-color:green; border-radius: 50px">Sign up</a>
      </div>
       {% endif %}
    </header>

    <div id="content">
        {% if messages %}
        {% endif %}
        {% block content %}{% endblock %}
    </div>

<body style="background: #E9F1EB; font-family: 'Poppins', sans-serif;">

 <script>
    setTimeout(function(){
      if ($('#msg').length > 0) {
        $('#msg').remove();
      }
    }, 2000)
  </script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>

booking/flights/templates/booked_tickets.html
{% extends 'base.html' %}
{% block content %}
<div>
    {% if ticket %}
{% for t in ticket %}
 <div class="alert alert-secondary" align="center" style="background: white; width: 600px; padding: 20px; left: 25%">
   <div class="box" style="display: inline-block; text-align: left; margin-right: 90px">
       <div style="display: flex; font-size: 30px">{{ t.flight.departure_city }}</div>
       <div style="display: flex; font-size: 20px; align-text: center">{{ t.flight.departure_time|date:'H:i'}}</div>
   </div>
      <div class="box" style="display: inline-block;">
          <p style="position: relative; right: 25px">
              <img src="/static/flight/arrow.png" width="80" height="50px" align="right"/>
          </p>
          </div>
     <div class="box" style="display: inline-block; margin-left: 15px; right: 70px">
         <div align="right" style="display: flex;font-size: 30px">{{ t.flight.destination_city }}</div>
       <div style="display: flex; font-size: 20px">{{ t.flight.arrival_time|date:'H:i' }}</div>
     </div>
     <div>
     <a class="btn btn-primary" style="align-items: center; background-color: #0d5528; --bs-btn-border-color: white; --bs-btn-hover-border-color:green; border-radius: 50px" href="{% url 'delete' t.id %}">Delete</a>
    </div>
 </div>
    {% endfor %}</div>
{% else %}
 <p align="center" style="font-size: 50px; padding: 10px; margin: 10px">Sorry :(</p>
<p align="center" style="font-size: 25px">There is no tickets yet!</p>
   <div class="button" align="center">
    <a href="{% url 'search' %}" type="button" class="btn btn-primary" style="background-color: #0d5528; --bs-btn-border-color: white; --bs-btn-hover-border-color:green; border-radius: 50px">BUY TICKETS</a>
   </div>
{% endif %}
{% endblock %}

booking/flights/templates/delete_order.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<p align="center" style="font-weight: bold; position: relative; top:20px">Are you sure you want to cancel ticket?</p>

<div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-5 text-center justify-content-center ">
              <form method="POST" align="center" >
                {% csrf_token %}
                <a href="{% url 'booked' %}" type="button" class="btn btn-outline-primary me-2" style="background-color: white; --bs-btn-border-color: #0d5528; --bs-btn-color: #0d5528; --bs-btn-hover-border-color:green; border-radius: 50px">Cancel</a>
                <input type="submit" value="Yes, I'm sure" class="btn btn-primary" style="background-color: #0d5528; --bs-btn-border-color: white; --bs-btn-hover-border-color:green; border-radius: 50px">
              </form>
            </div>
        </div>
</div>
{% endblock %}

booking/flights/templates/dropdown_list.html
<option value="">---------</option>
{% for airport in airports %}
<option value="{{ airport.pk }}">{{ airport.title }}</option>
{% endfor %}

booking/flights/templates/index.html
{% extends 'base.html' %}
{% block content %}

<body style="background-image: url(../static/plane1.jpg); no repeat; position: relative; background-size: cover;">
<h1 style="color: white; padding: 50px; font-size: 60px; font-family: 'Inter'; font-weight: 800;">WELCOME TO FLIGHTS</h1>
<a href="{% url 'search' %}" type="button" class="btn btn-primary" style="font-size: 33px; text-align: center; margin: 10px; position:fixed; left:280px; top:230px; width: 170px; height: 70px; background-color: white; --bs-btn-border-color: #0d5528; --bs-btn-color: #0d5528; --bs-btn-hover-border-color:#0d5528; border-radius: 50px">Start</a>
</body>
{% endblock %}

booking/flights/templates/ticket_booked.html
{% extends 'base.html' %}
{% block title %}Ticket{% endblock %}
{% block content %}
<div style="padding: 10px; margin: 30px">
    <h1 align="center">Thank you</h1>
    <p align="center">Your order has been successfully completed!</p>
</div>
<div class="button" align="center">
    <a href="/" type="button" class="btn btn-primary" style="background-color: #0d5528; --bs-btn-border-color: white; --bs-btn-hover-border-color:green; border-radius: 50px">Back to Home</a>
   </div>
{% endblock %}

booking/flights/templates/ticket_search.html
{% extends 'base.html' %}
{% block content %}
<div>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-danger" id="msg" role="alert" style="width: 500px; height: 10px; padding: 30px">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
</div>

<h3 align="center" style="font-weight: bold; position: relative; top:10px">Select the data to search for tickets</h3>


<div class="container">
        <div class="row justify-content-center align-items-center">
            <div class="col-5 text-center justify-content-center ">
                <form method="GET" action="" id="SearchForm" data-airports-url="{% url 'ajax_load_airports' %}">
                    {{ form.as_p }} <p style="font-weight: bold;">Value: less than <span id="demo"></span>$</p>
                    <script>
                        var slider = document.getElementById("range-field");
                        var output = document.getElementById("demo");
                        output.innerHTML = slider.value;

                        slider.oninput = function() {
                        output.innerHTML = this.value;
                        }
                    </script>
                <input type="submit" class="btn btn-outline-success" style="background-color: #0d5528; --bs-btn-color: white; --bs-btn-border-color: white; --bs-btn-hover-border-color:green; border-radius: 50px" value="Search">

                </form>
            </div>
        </div>
    </div>


<div class="container" style="background: white; border-radius: 50px">
    <table class="table table-striped table-hover" style="border-radius: 50px">
        <tr style="border-radius: 50px">
            <th>Departure city</th>
            <th>Departure airport</th>
            <th>Destination city</th>
            <th>Destination airport</th>
            <th>Departure date</th>
            <th>Arrival date</th>
            <th>Price</th>
            <th>Buy</th>
        </tr>
    {% for ticket in queryset %}
        <tr style="border-radius: 50px">
            <td style="font-weight: bold; font-size: 20px">{{ ticket.departure_city }}</td>
            <td style="position: relative; width: 200px">{{ ticket.departure_airport }}</td>
            <td style="font-weight: bold; font-size: 20px">{{ ticket.destination_city }}</td>
            <td style="position: relative; width: 200px">{{ ticket.destination_airport }}</td>
            <td><p>{{ ticket.departure_date|date:"d F"  }}</p>
                <p style="font-weight: bold">{{ ticket.departure_time|date:'H:i' }}</p></td>
            <td><p>{{ ticket.arrival_date|date:"d F" }}</p>
                <p style="font-weight: bold">{{ ticket.arrival_time|date:'H:i' }}</p></td>
            <td style="font-weight: bold; font-size: 20px">{{ ticket.price }}$</td>
            <td style="position: relative; align-items: center; margin-left: 10px; margin-top: 10px"><a href="/booking/{{ticket.id}}" class="btn btn-primary" style="background-color: white; --bs-btn-border-color: #0d5528; --bs-btn-color: #0d5528; --bs-btn-hover-border-color:green; border-radius: 50px; width: 60px; height: 30px; font-size: 12px; display: flex;  justify-content: center; align-items: center;"><i class="fa-solid fa-plane" style="color: #0d5528"></i>Buy</a></td>
        </tr>
</div>
    {% endfor %}
    </table>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_departure_city").change(function () {
        const url = $("#SearchForm").attr("data-airports-url");
        const city_airportId = $(this).val();

        $.ajax({
            url: url,
            data: {
                'city_airport_id': city_airportId
            },
            success: function (data) {
                $("#id_departure_airport").html(data);
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (departure_airport) {
                    html_data += `<option value="${departure_airport.id}">${departure_airport.title}</option>`
                });
                console.log(html_data);
                $("#id_departure_airport").html(html_data);

                */
            }
        });

    });

    $("#id_destination_city").change(function () {
        const url = $("#SearchForm").attr("data-airports-url");
        const city_airportId = $(this).val();

        $.ajax({
            url: url,
            data: {
                'city_airport_id': city_airportId
            },
            success: function (data) {
                $("#id_destination_airport").html(data);
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (destination_airport) {
                    html_data += `<option value="${destination_airport.id}">${destination_airport.title}</option>`
                });
                console.log(html_data);
                $("#id_destination_airport").html(html_data);

                */
            }
        });

    });
</script>

{% endblock %}